### ISSUE TITLE
Suggestion: add a code linter

### ISSUE THREAD

**Issue by ghost** [Luna-devv/dlist.js#2]
## Why a linter is necessary
As this project evolves, it’s inevitable that there will be bugs introduced that the TypeScript compiler simply isn’t designed to detect. A linter such as ESLint, with the help of the TypeScript ESLint parser, can detect issues like [stringifying an object](https://typescript-eslint.io/rules/no-base-to-string), [forgetting to handle promise rejections](https://typescript-eslint.io/rules/no-floating-promises), or [misusing `any`](https://typescript-eslint.io/rules/no-explicit-any) (which is, frankly, defeats the purpose of using TypeScript and is an accident waiting to happen). It can also enforce stylistic decisions, like [consistent privacy modifiers on classes](https://typescript-eslint.io/rules/explicit-member-accessibility) and the [usage of namespaces](https://typescript-eslint.io/rules/no-namespace).

## TSLint vs ESLint

While the TSLint linter is clearly designed for TypeScript, it has been deprecated and superseded by ESLint with the typescript-eslint parser. I would recommend using ESLint.

**Comment by Luna-devv** [comment]
done with e7e48e0674de5474028332d991ee1a8c8e98572b
